# Generated by Django 4.1.4 on 2023-01-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_alter_director_name_alter_movie_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(default=0, null=True, verbose_name='Рейтинг'),
        ),
    ]
