# Generated by Django 4.1.4 on 2023-01-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0009_alter_movie_created_date_alter_movie_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
